### ISSUE TITLE
Set-up Checklist

### ISSUE THREAD

**Issue by cici-chen** [cici-chen/tech-support-onboarding#1]
# Setup checklist

Here are all the software, logins, and permissions you'll need to get started supporting, plus a few other things. Feel free to check off each item as you go.

## Hardware

- [ ] Grab your new hardware. Let your buddy know if your hardware differs from what you've ordered.
- [ ] Register your laptop at https://gear.githubapp.com

## Software

**Download the following programs:**

- [ ] [Slack](https://slack.com/downloads)
- [ ] [GitHub Desktop](https://desktop.github.com/)
- [ ] [Atom](https://atom.io/)
- [ ] [1Password](https://gear.githubapp.com/apps/21)
- [ ] [TextExpander](https://gear.githubapp.com/apps/64)

**Mobile**

* Slack
* Team (https://speakeasy.githubapp.com/)

(These are optional – don't feel obligated to download mobile apps if that doesn't fit in with your work/life balance!)

## Installations and permissions

**Site Admin access**

- [ ] Browse to https://github.com/stafftools and check if you see the admin backend. If so, you're good. If not, your buddy needs to promote you to site admin.
- [ ] Buddy: Open a PR in `github/github` to add new hire to the [staff `CAN_UNLOCK` list](https://github.com/github/github/blob/master/app/models/user/roles_dependency.rb#L4), cc `@github/security-ops`, and wait for a :+1: before merging.

**GitHub teams and orgs**

Your buddy should add you to the following important work teams on GitHub.com:

- [ ] Employees
- [ ] Support
- [ ] Support-Technical

_Buddy: If you don't have sufficient rights to do that, refer to the security team's [How to get access to X](https://githubber.com/article/crafts/security/how-do-i-get-access-to-x) Guide and reach out to the person in charge._

**Chat**

- [ ] Slack
    * Sign in using [Okta](https://github.okta.com/)
    * Add some channels!
        * [#announcements](https://github.slack.com/messages/announcements/)
        * [#support](https://github.slack.com/messages/support/)
        * [#support-technical](https://github.slack.com/messages/support-technical/)
        * [#support-shiftlog](https://github.slack.com/messages/support-shiftlog/)
    * Add additional "Highlight words" to your Slack notifications settings. For example, most support people get pings for the word "supportocats" in addition to their personal mentions.

**Hubot**

You'll be interacting multiple times a day with Hubot, our friendly robot. Hubot doesn't know you yet, so we'll need to take care of introducing the two of you.

- [ ] Introduce yourself to Hubot in Chat via `.i am <username>`.
- [ ] Register your laptop's Mac address via `.mac me`. If you're running into any issues with that, let your buddy know.

**GitHub Desktop**

Install the Desktop app you downloaded earlier, and sign into your account. You may also be interested in checking out the [Desktop Help docs](https://help.github.com/desktop/).

**Strap**

Strap is a script to bootstrap a minimal OS X development system. It installs the minimal set of software that OS X developers at GitHub will want. This will set up the environment on your machine to coexist happily with the tools we use at GitHub.

Install Strap using the instructions here: https://strap.githubapp.com

**SSH**

Create an SSH key on your machine, and add it to your GitHub account, as shown in our [Help docs](https://help.github.com/articles/generating-ssh-keys/).

**Calendars**

- [ ] Add the following calendars to your Google calendar:
    * Support - `github.com_n5217futrn8hlqhk5lhdrvicjk@group.calendar.google.com`
    * Support coverage - `github.com_mjprej5lqeefnj8ioj8jiobq60@group.calendar.google.com)`
    * NA Technical Out of Office (OoO) - `github.com_fksh0mrjueg360jvlnjni3pj20@group.calendar.google.com`
    * International Technical Out of Office (OoO) - `github.com_fksh0mrjueg360jvlnjni3pj20@group.calendar.google.com`
    * Your buddy's calendar - Click in the "Add a coworker's calendar" field under "Other calendars" and start typing their name

- [ ] [Triage signup](https://calendar.google.com/calendar/selfsched?sstoken=UUJQM1p0SHlzNjZlfGRlZmF1bHR8NmRhYWNiYTFiNjdmZTFmOGE4MjM5YWJjNTA3NDVhMDY&pli=1) - Bookmark this and use it to sign up for triage shifts

- [ ] Read the [Viewing shared calendars](https://githubber.com/article/tools/calendars/viewing-the-shared-calendars) and subscribe to some of them. A good start is to subscribe to:
    * GitHub (Company-wide events)
    * Out of Office (Company-wide out of office calendar)

- [ ] [Athena](https://athena.githubapp.com/) - The app we use for managing weekend shifts

- [ ] [Web Support Schedule repo](https://github.com/github/web-support-schedule) - For out of office, vacation, HQ visits, or reduced availability

**Storage and passwords**

- [ ] Box: You should have an invite in your email already, but let your buddy know if you don't. After that you can follow the steps in this GitHubber article on [how to set up your Box account](https://githubber.com/article/tools/box/setting-up-your-box-account)

**Notifications**

GitHub's settings don't currently allow you filter your notifications by team mention, personal mention, etc. So once you start receiving a ton of notifications from all of the repositories you're watching, you may want to consider one of these notification management tools:

* [Octobox](https://octobox.githubapp.com/): A web app for notifications. See this [Team post](https://team.githubapp.com/posts/29359)
 for more information.
* [OctoGas Gmail extension](https://github.com/mastahyeti/OctoGAS): A Google Apps script you can add to your Gmail, which will create and manage labels in your inbox to break out notifications by team mentions, personal mentions, etc. Take a look at the project's README file for further details.

## Other stuff

**Security**

Talk to your buddy about how to [contact security](https://github.com/github/security) if something gets lost or stolen and how to contact them [in an emergency](https://githubber.com/article/crafts/security/urgent-security-issues).

**Team**

Team is one of the most important internal apps here at GitHub. You'll want to frequently check what's going on in the GitHub Universe™.

- [ ] Browse to https://team.githubapp.com/settings and fill out all the nitty, gritty details so that we can learn something about you.
- [ ] Check out another GitHubber's profile. For instance, this is [@defunkt's profile](https://team.githubapp.com/defunkt), GitHub's CEO.

**Sign up for affinity groups**

GitHub is made up of people with many different backgrounds and lifestyles, but being distributed can make it harder to find them all. Check out this [GitHubber article](https://githubber.com/article/getting-started/GitHubber-Life-for-Infinity-and-Beyond/find-your-people) to find your people.

- [ ] Ask to join any affinity teams on GitHub.com that strike your fancy
- [ ] Watch the repositories for those teams
- [ ] Join some fun Slack channels
